#!/bin/bash
#
# Clone WSJT-X current installation under /usr to /usr/local and modify it to use multi
# Use start-multi to start the two WSJT-X instances. See README.md for instructions how 
# to set them up.
#
# This will work with: aur/wsjtx-improved, aur/wsjtx-git, and aur/wsjtx
# If multiple wsjtx packages installed then this picks up wsjtx-improved
#
# Note: This will only work on Arch Linux or derivatives which use pacman package manager.
#
# Warning: This will overwrite any existing wsjtx installation under /usr/local !
#
if [ ! -e /usr/bin/pacman ]; then
  echo "Pacman package manager missing (not using Arch Linux?)"
  exit 1
fi

if pacman -Qi wsjtx &>/dev/null; then 
  package=wsjtx;
fi
if pacman -Qi wsjtx-git &>/dev/null; then 
  package=wsjtx-git;
fi
if pacman -Qi wsjtx-improved &>/dev/null; then 
  package=wsjtx-improved;
fi
if [ "$package" == "" ]; then
  echo "WSJT-X package not installed."
  exit 0
fi

for file in `pacman -Ql $package | cut -d\  -f2`; do
  install -D $file `echo $file | sed -e "s-/usr/-/usr/local/-g"`
done
mv /usr/local/bin/jt9 /usr/local/bin/jt9.x
ln -s /usr/local/bin/multi /usr/local/bin/jt9
install -D multi /usr/local/bin
install -D start-multi /usr/local/bin
exit 0
