#!/bin/bash
export MYCALL=AA6KJ
# export COLLECT_STATS=/home/eloranta/stats.out
# export FILTER=/home/eloranta/cty.dat
# export CONTINENT=EU
# export PASS_THROUGH=""

/usr/local/bin/wsjtx &
/usr/local/bin/wsjtx -r 2
killall /usr/local/bin/jt9
killall /usr/local/bin/jt9.x
exit 0
